export const legalLinks = `<nav class="legal-links" aria-label="Legal and contact"><a href="https://acousticbeacon.com/privacy">Privacy</a><a href="https://acousticbeacon.com/terms">Terms</a><a href="https://acousticbeacon.com/privacy/choices">Privacy Choices</a><a href="https://acousticbeacon.com/contact">Contact</a></nav>`;
export function signupForm(loading=false) {
 return `<h1>Create your<br>Merchant account.</h1><p>Your business. Your offers. Your own workspace.</p><form data-form="production-signup"><label>Business name<input name="business_name" autocomplete="organization" required maxlength="200"></label><label>Contact name<input name="contact_name" autocomplete="name" required maxlength="200"></label><label>Website (optional)<input name="website" type="text" inputmode="url" placeholder="yourbusiness.com" maxlength="2048"></label><label class="check-row"><input name="directory_opt_in" type="checkbox"><span>List my business in the Acoustic Beacon business directory<small>Show your business on AcousticBeacon.com with a link to your website.</small></span></label><label>Email<input name="email" type="email" autocomplete="username" required maxlength="320"></label><label>Password<input name="password" type="password" autocomplete="new-password" required minlength="15" maxlength="256"></label><small>Use at least 15 characters.</small><label>Confirm password<input name="confirm_password" type="password" autocomplete="new-password" required minlength="15" maxlength="256"></label><p class="form-error" role="alert"></p><p class="legal-notice">By creating an account, you agree to the <a href="https://acousticbeacon.com/terms">Terms of Use</a> and acknowledge the <a href="https://acousticbeacon.com/privacy">Privacy Policy</a>.</p><button class="button wide" type="submit" ${loading?'disabled':''}>Create Merchant Account</button></form><p class="small">Already have an account? <a href="/merchant/">Sign In</a></p>${legalLinks}`;
}
export function registrationPayload(form) {
 const password=form.get('password'),confirm=form.get('confirm_password');
 if(password.length<15)throw Error('Use a password of at least 15 characters.');
 if(password!==confirm)throw Error('Passwords must match.');
 return {website:form.get('website')||null,directory_opt_in:form.has('directory_opt_in'),business_name:form.get('business_name'),contact_name:form.get('contact_name'),email:form.get('email'),password,confirm_password:confirm};
}
