import {escapeHtml as e, statusOf, safeImage} from './domain.js';
export const icon = (name, size = 20) => {
  const paths = {grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',tag:'M20 13l-7 7-10-10V3h7z M7 7h.01',layers:'M12 3L2 8l10 5 10-5z M2 12l10 5 10-5 M2 16l10 5 10-5',beacon:'M5 5a10 10 0 0 0 0 14 M19 5a10 10 0 0 1 0 14 M8 8a6 6 0 0 0 0 8 M16 8a6 6 0 0 1 0 8 M12 10v4',activity:'M2 12h5l3-8 4 16 3-8h5',user:'M20 21v-2a7 7 0 0 0-14 0v2 M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8',arrow:'M5 12h14 M13 6l6 6-6 6',plus:'M12 5v14 M5 12h14',search:'M21 21l-5-5 M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14',close:'M6 6l12 12 M6 18L18 6',menu:'M4 6h16 M4 12h16 M4 18h16',check:'M5 12l4 4L19 6',logout:'M9 5H4v14h5 M10 12h11 M17 8l4 4-4 4',clock:'M12 8v5l3 2 M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20'};
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.grid}"/></svg>`;
};
export const pill = (status) => `<span class="pill ${e(status)}"><i></i>${e(status[0].toUpperCase()+status.slice(1))}</span>`;
export const button = (text, action, secondary = false, attrs = '') => `<button class="button ${secondary ? 'secondary' : ''}" data-action="${action}" ${attrs}>${e(text)}</button>`;
export const empty = (title, text, action = '') => `<div class="empty"><div class="empty-icon">${icon('layers',28)}</div><h3>${e(title)}</h3><p>${e(text)}</p>${action}</div>`;
const offerRow = (o, manager) => `<tr><td><div class="record"><span class="record-icon">${icon('tag')}</span><div><strong>${e(o.title)}</strong><small>${e(manager ? o.merchant : o.description.slice(0,72))}</small></div></div></td><td>${pill(statusOf(o))}</td><td><span class="network-label">${o.manager_eligible ? 'Network eligible' : 'Merchant only'}</span></td><td><button class="text-button" data-action="${manager ? 'preview-offer' : 'edit-offer'}" data-id="${e(o.id)}">${manager ? 'View' : 'Edit'} ${icon('arrow',16)}</button></td></tr>`;
export function offersTable(offers, manager) {
  return offers.length ? `<div class="table-scroll"><table><thead><tr><th>Offer</th><th>Status</th><th>Visibility</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>${offers.map(o=>offerRow(o,manager)).join('')}</tbody></table></div>` : empty('Your next offer starts here','Create something your customers will want to discover.',manager ? '' : button('Create offer','new-offer'));
}
export function overview(w, activityCard) {
  const activeOffers = w.offers.filter(o=>statusOf(o)==='active').length;
  const activeCampaigns = w.campaigns.filter(o=>statusOf(o)==='active').length;
  const activeBeacons = w.beacons.filter(b=>b.active).length;
  const manager = w.account.role==='manager';
  return `<div class="page-intro"><div><span class="eyebrow">YOUR WORKSPACE, AT A GLANCE</span><h1>Make every signal count<span>.</span></h1><p>Fresh offers. Connected campaigns. More reasons to stop by.</p></div>${button(manager ? 'Create campaign' : 'Create offer',manager ? 'new-campaign' : 'new-offer')}</div>
  <div class="stats">${[[activeOffers,'Active offers','Available to customers','tag'],[activeCampaigns,'Active campaigns','Ready to connect','layers'],[activeBeacons,'Active beacons','Assigned to your account','beacon']].map(([n,t,s,i])=>`<section class="stat"><div class="stat-top"><span>${t}</span>${icon(i)}</div><strong>${n}</strong><small>${s}</small></section>`).join('')}${activityCard}</div>
  <div class="overview-grid"><section class="panel"><div class="panel-heading"><div><h2>${manager ? 'Network offers' : 'Your latest offers'}</h2><p>${manager ? 'Shared by participating merchants.' : 'Keep your next discovery ready.'}</p></div><a href="#/offers" class="text-button">View all ${icon('arrow',16)}</a></div>${offersTable(w.offers.slice(0,4),manager)}</section>
  <section class="panel signal-panel"><span class="eyebrow">ONE SIGNAL. MORE POSSIBILITY.</span><div class="signal-mark">${icon('beacon',44)}</div><h2>Your content can change.<br>Your beacon stays the same.</h2><p>A beacon points to a campaign. You choose which offers customers discover.</p><div class="mini-flow"><span>Beacon</span><b>→</b><span>Campaign</span><b>→</b><span>Offers</span></div><a href="#/beacon" class="text-button">Manage your beacon ${icon('arrow',16)}</a></section></div>
  <section class="panel"><div class="panel-heading"><div><h2>Campaigns in your workspace</h2><p>A collection of offers, ready for a single signal.</p></div>${button('Create campaign','new-campaign',true)}</div>${campaignCards(w,true)}</section>`;
}
export function campaignCards(w, compact=false) {
  return w.campaigns.length ? `<div class="campaign-grid ${compact?'compact':''}">${w.campaigns.map(c=>{
    const linked=w.beacons.filter(b=>b.campaign_id===c.id);
    return `<article class="campaign-card"><div class="card-top"><span class="record-icon">${icon('layers')}</span>${pill(statusOf(c))}</div><h3>${e(c.name)}</h3><p>${c.offer_ids.length} selected offer${c.offer_ids.length===1?'':'s'}${c.sample?' · Sample campaign':''}</p><div class="card-footer"><span>${linked.length ? linked.map(b=>e(b.beacon_id)).join(', ') : 'No beacon assigned'}</span><button class="text-button" data-action="edit-campaign" data-id="${e(c.id)}">Manage ${icon('arrow',16)}</button></div></article>`;
  }).join('')}</div>` : empty('Bring your offers together','Create a campaign and choose the offers it will serve.',button('Create campaign','new-campaign'));
}
export function beaconPage(w, demo=false) {
  const support=w.account.role==='manager' && w.support_beacons ? `<section class="panel"><h2>Merchant beacon support</h2><p>Assignments are automatic and permanent. Suspend or restore delivery for support; ownership cannot be changed here.</p>${w.support_beacons.map(b=>`<form class="assignment" data-form="beacon-support" data-id="${e(b.id)}"><strong>${e(b.business)} � ${e(b.beacon_id)}</strong><label class="check-row"><input type="checkbox" name="active" ${b.active?'checked':''}>Delivery enabled</label><button class="button secondary" type="submit">Save availability</button><p class="form-error" role="alert"></p></form>`).join('')}</section>`:'';
  return `${support}<div class="page-intro"><div><span class="eyebrow">THE CONNECTION TO YOUR CUSTOMERS</span><h1>Your beacon</h1><p>One identifier. A collection of offers you control.</p></div></div>${w.beacons.length ? w.beacons.map(b=>{
    const campaign=w.campaigns.find(c=>c.id===b.campaign_id);
    return `<section class="beacon-hero panel"><div class="beacon-orbit">${icon('beacon',58)}</div><div><span class="eyebrow">BEACON ID</span><h2 class="beacon-id">${e(b.beacon_id)}</h2>${pill(b.active?'active':'inactive')}<p>This beacon identifies a campaign, not a single offer.</p></div><div class="beacon-meta"><span>Currently served offers</span><strong>${b.served_offers.length}</strong><small>From the backend's active-content rules</small></div></section>
    ${demo?'':`<section class="panel"><h2>Play your beacon</h2><p>Create an active offer and campaign, then connect the campaign below. Play this audio through your speaker while customers listen with Acoustic Beacon. Start at a comfortable volume.</p><audio controls preload="none" aria-label="Play your assigned beacon" src="/api/v1/dashboard/beacons/${e(b.id)}/audio.wav"></audio><p><a class="button secondary" download href="/api/v1/dashboard/beacons/${e(b.id)}/audio.wav">Download beacon audio</a></p><p class="help">Three transmissions per file. Your audio stays the same when you update offers. Playback starts only when you press Play.</p></section>`}
      <section class="panel"><div class="panel-heading"><div><h2>Connected campaign</h2><p>Change your collection without changing the beacon or its audio.</p></div></div><form class="assignment" data-form="assignment" data-id="${e(b.id)}"><label>Campaign<select name="campaign_id"><option value="">No campaign assigned</option>${w.campaigns.map(c=>`<option value="${e(c.id)}" ${b.campaign_id===c.id?'selected':''}>${e(c.name)}</option>`).join('')}</select></label><button class="button" type="submit">Save assignment</button><p class="form-error" role="alert"></p></form><div class="delivery-flow"><div><small>01 · SOURCE</small><strong>${e(b.beacon_id)}</strong></div>${icon('arrow')}<div><small>02 · CAMPAIGN</small><strong>${e(campaign?.name || 'Unassigned')}</strong></div>${icon('arrow')}<div><small>03 · DELIVERY</small><strong>${b.served_offers.length} active offers</strong></div></div></section>
    <section class="panel"><div class="panel-heading"><div><h2>What customers can discover now</h2><p>Resolved by the same service used by the consumer app.</p></div></div>${b.served_offers.length ? `<div class="served-grid">${b.served_offers.map(o=>`<article><span class="record-icon">${icon('tag')}</span><div><h3>${e(o.title)}</h3><p>${e(o.merchant.name)}</p><small>${e(o.description)}</small></div></article>`).join('')}</div>` : empty('No offers are being served','Choose an active campaign with active, authorized offers.')}</section>`;
  }).join('') : `<section class="panel">${empty('No beacon is assigned to this account','Your account has no available beacon. Refresh your workspace; if this persists, contact support.')}</section>`}
  <p class="footnote">Only active, in-date offers in your connected campaign are delivered to customers.</p>`;
}
export function accountPage(w) { return `<div class="page-intro"><div><span class="eyebrow">YOUR WORKSPACE</span><h1>Account</h1><p>Business details and access, all in one place.</p></div></div><section class="panel account-panel"><div class="account-cover"><img src="/merchant/beacon-logo.png" alt="Acoustic Beacon"><div><h2>${e(w.account.business)}</h2><p>${e(w.account.description)}</p></div></div><dl class="account-details"><div><dt>Email</dt><dd>${e(w.account.email)}</dd></div><div><dt>Role</dt><dd>${e(w.account.role)}</dd></div><div><dt>Workspace</dt><dd>Local development · sample data</dd></div><div><dt>Authentication</dt><dd>Development session · production sign-in not connected</dd></div></dl>${w.account.role==='merchant'?`<form class="assignment" data-form="directory-profile"><label>Website<input name="website" value="${e(w.account.website||'')}" placeholder="yourbusiness.com" maxlength="2048"></label><label class="check-row"><input name="directory_opt_in" type="checkbox" ${w.account.directory_opt_in?'checked':''}><span>List my business in the Acoustic Beacon business directory<small>Only your business name and website will be public. Uncheck to remove your listing.</small></span></label><div class="form-error" role="alert"></div><button class="button" type="submit">Save website and directory preference</button></form>`:''}<div class="account-bottom"><p>Billing is not available in this phase.</p>${button('Sign out','sign-out',true)}</div></section>`; }
export function preview(offer={}) {
  const img=safeImage(offer.image_url);
  return `<div class="offer-preview"><div class="preview-art">${img?`<img src="${e(img)}" alt="Offer promotional image">`:icon('beacon',46)}</div><div class="preview-copy"><span class="eyebrow">CUSTOMER PREVIEW</span><small>${e(offer.merchant || 'Your business')}</small><h3 id="preview-title">${e(offer.title || 'Your offer headline')}</h3><p id="preview-description">${e(offer.description || 'Help customers understand what makes this offer worth discovering.')}</p><span class="preview-note">Content appears inside Acoustic Beacon.</span></div></div>`;
}
