"""initial_schema

Revision ID: 0001
Revises:
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('merchant', 'manager')", name='ck_user_role'),
    sa.CheckConstraint('email = lower(trim(email)) AND length(email) > 3', name='ck_user_email_normalized'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('merchants',
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL AND latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)', name='ck_merchant_coordinates'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_merchant_name'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_merchants_owner_user_id'), 'merchants', ['owner_user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sample', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(merchant_id IS NOT NULL AND manager_user_id IS NULL) OR (merchant_id IS NULL AND manager_user_id IS NOT NULL)', name='ck_campaign_one_owner'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_campaign_name'),
    sa.CheckConstraint('start_at IS NULL OR end_at IS NULL OR end_at > start_at', name='ck_campaign_window'),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_campaigns_manager_user_id'), 'campaigns', ['manager_user_id'], unique=False)
    op.create_index(op.f('ix_campaigns_merchant_id'), 'campaigns', ['merchant_id'], unique=False)
    op.create_table('offers',
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('manager_eligible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_offer_title'),
    sa.CheckConstraint('start_at IS NULL OR end_at IS NULL OR end_at > start_at', name='ck_offer_window'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_offers_merchant_id'), 'offers', ['merchant_id'], unique=False)
    op.create_table('beacons',
    sa.Column('payload_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('payload_id BETWEEN 0 AND 16777215', name='ck_beacon_24bit'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payload_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_beacons_campaign_id'), 'beacons', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_beacons_owner_user_id'), 'beacons', ['owner_user_id'], unique=False)
    op.create_table('campaign_offers',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_campaign_offer_order'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('campaign_id', 'offer_id')
    )
    op.create_index(op.f('ix_campaign_offers_offer_id'), 'campaign_offers', ['offer_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_offers_offer_id'), table_name='campaign_offers')
    op.drop_table('campaign_offers')
    op.drop_index(op.f('ix_beacons_owner_user_id'), table_name='beacons')
    op.drop_index(op.f('ix_beacons_campaign_id'), table_name='beacons')
    op.drop_table('beacons')
    op.drop_index(op.f('ix_offers_merchant_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_campaigns_merchant_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_manager_user_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_merchants_owner_user_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_table('users')
    # ### end Alembic commands ###
